In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("Datasets/direct_marketing.csv")

In [3]:
df

,recency,history_segment,history,mens,womens,zip_code,newbie,channel,segment,visit,conversion,spend,DM_category
0,10,2) $100 - $200,142.44,1,0,Surburban,0,Phone,Womens E-Mail,0,0,0.0,4
1,6,3) $200 - $350,329.08,1,1,Rural,1,Web,No E-Mail,0,0,0.0,11
2,7,2) $100 - $200,180.65,0,1,Surburban,1,Web,Womens E-Mail,0,0,0.0,1
3,9,5) $500 - $750,675.83,1,0,Rural,1,Web,Mens E-Mail,0,0,0.0,2
4,2,1) $0 - $100,45.34,1,0,Urban,0,Web,Womens E-Mail,0,0,0.0,4
5,6,2) $100 - $200,134.83,0,1,Surburban,0,Phone,Womens E-Mail,1,0,0.0,1
6,9,3) $200 - $350,280.20,1,0,Surburban,1,Phone,Womens E-Mail,0,0,0.0,4
7,9,1) $0 - $100,46.42,0,1,Urban,0,Phone,Womens E-Mail,0,0,0.0,1
8,9,5) $500 - $750,675.07,1,1,Rural,1,Phone,Mens E-Mail,0,0,0.0,5
9,10,1) $0 - $100,32.84,0,1,Urban,1,Web,Womens E-Mail,0,0,0.0,1
10,7,5) $500 - $750,548.91,0,1,Urban,1,Phone,Womens E-Mail,1,0,0.0,1
11,1,3) $200 - $350,211.45,0,1,Urban,1,Phone,Womens E-Mail,0,0,0.0,1
12,5,5) $500 - $750,642.90,0,1,Surburban,1,Multichannel,Womens E-Mail,0,0,0.0,1
13,2,2) $100 - $200,101.64,0,1,Urban,0,Web,Mens E-Mail,1,0,0.0,3
14,4,3) $200 - $350,241.42,0,1,Rural,1,Multichannel,No E-Mail,0,0,0.0,5
15,3,1) $0 - $100,58.13,1,0,Urban,1,Web,No E-Mail,1,0,0.0,6
16,5,1) $0 - $100,29.99,1,0,Surburban,0,Phone,Mens E-Mail,0,0,0.0,2
17,9,2) $100 - $200,112.35,1,0,Rural,0,Web,Mens E-Mail,0,0,0.0,2
18,11,3) $200 - $350,219.04,1,1,Surburban,0,Phone,Mens E-Mail,0,0,0.0,5
19,5,"6) $750 - $1,000",828.42,1,0,Surburban,1,Multichannel,Mens E-Mail,0,0,0.0,2
20,9,1) $0 - $100,29.99,0,1,Surburban,1,Phone,No E-Mail,0,0,0.0,5
21,11,2) $100 - $200,182.32,1,0,Surburban,0,Phone,Mens E-Mail,0,0,0.0,2
22,2,2) $100 - $200,118.40,1,0,Surburban,0,Web,Mens E-Mail,1,0,0.0,2
23,2,1) $0 - $100,29.99,0,1,Urban,1,Phone,No E-Mail,0,0,0.0,5
24,4,1) $0 - $100,78.24,1,0,Surburban,0,Web,No E-Mail,0,0,0.0,6
25,6,2) $100 - $200,139.87,0,1,Rural,1,Web,Mens E-Mail,0,0,0.0,3
26,12,2) $100 - $200,115.39,0,1,Surburban,0,Phone,Mens E-Mail,1,0,0.0,3
27,6,2) $100 - $200,162.98,0,1,Surburban,0,Web,Mens E-Mail,0,0,0.0,3
28,7,4) $350 - $500,435.73,0,1,Urban,1,Web,No E-Mail,0,0,0.0,5
29,2,3) $200 - $350,203.35,1,0,Rural,0,Web,No E-Mail,0,0,0.0,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...
63970,4,2) $100 - $200,191.15,0,1,Surburban,1,Web,Womens E-Mail,0,0,0.0,1
63971,5,5) $500 - $750,549.87,0,1,Surburban,1,Phone,Womens E-Mail,0,0,0.0,1
63972,3,5) $500 - $750,554.97,0,1,Surburban,1,Web,No E-Mail,0,0,0.0,5
63973,8,4) $350 - $500,471.80,1,0,Surburban,1,Multichannel,Womens E-Mail,0,0,0.0,4
63974,8,1) $0 - $100,73.65,0,1,Surburban,0,Phone,Mens E-Mail,0,0,0.0,3
63975,10,"6) $750 - $1,000",883.92,1,0,Urban,1,Phone,No E-Mail,0,0,0.0,6
63976,1,5) $500 - $750,710.72,1,1,Urban,1,Phone,No E-Mail,0,0,0.0,11
63977,8,1) $0 - $100,29.99,0,1,Surburban,0,Web,No E-Mail,1,0,0.0,5
63978,10,2) $100 - $200,102.01,0,1,Urban,1,Phone,Mens E-Mail,0,0,0.0,3
63979,10,2) $100 - $200,168.21,0,1,Surburban,0,Phone,No E-Mail,0,0,0.0,5
63980,3,4) $350 - $500,487.10,0,1,Surburban,1,Phone,No E-Mail,0,0,0.0,5
63981,4,2) $100 - $200,125.53,0,1,Rural,1,Phone,No E-Mail,0,0,0.0,5
63982,5,1) $0 - $100,29.99,1,0,Urban,1,Phone,Mens E-Mail,0,0,0.0,2
63983,2,1) $0 - $100,83.03,0,1,Urban,0,Phone,No E-Mail,0,0,0.0,5
63984,2,3) $200 - $350,209.51,0,1,Urban,1,Web,Womens E-Mail,0,0,0.0,1
63985,9,1) $0 - $100,29.99,1,0,Urban,0,Phone,Mens E-Mail,1,0,0.0,2
63986,9,1) $0 - $100,35.26,0,1,Urban,1,Web,Womens E-Mail,0,0,0.0,1
63987,1,1) $0 - $100,79.70,1,0,Surburban,1,Web,No E-Mail,0,0,0.0,6
63988,6,1) $0 - $100,32.98,1,0,Surburban,0,Web,Mens E-Mail,0,0,0.0,2
63989,10,3) $200 - $350,304.30,1,1,Surburban,0,Web,Womens E-Mail,1,0,0.0,5
63990,6,1) $0 - $100,80.02,0,1,Surburban,0,Phone,No E-Mail,0,0,0.0,5
63991,1,3) $200 - $350,306.10,1,0,Surburban,1,Phone,Womens E-Mail,0,0,0.0,4
63992,1,5) $500 - $750,519.69,1,1,Urban,1,Phone,Mens E-Mail,0,0,0.0,5
63993,4,4) $350 - $500,374.07,0,1,Surburban,0,Phone,Womens E-Mail,0,0,0.0,1
63994,7,1) $0 - $100,86.46,0,1,Urban,0,Web,Mens E-Mail,0,0,0.0,3
63995,10,2) $100 - $200,105.54,1,0,Urban,0,Web,Mens E-Mail,0,0,0.0,2
63996,5,1) $0 - $100,38.91,0,1,Urban,1,Phone,Mens E-Mail,0,0,0.0,3
63997,6,1) $0 - $100,29.99,1,0,Urban,1,Phone,Mens E-Mail,0,0,0.0,2
63998,1,5) $500 - $750,552.94,1,0,Surburban,1,Multichannel,Womens E-Mail,0,0,0.0,4
63999,1,4) $350 - $500,472.82,0,1,Surburban,0,Web,Mens E-Mail,0,0,0.0,3

# column indexing

In [5]:
df["recency"].head()

0    10
1     6
2     7
3     9
4     2
Name: recency, dtype: int64

In [7]:
df.recency.tail()

63995    10
63996     5
63997     6
63998     1
63999     1
Name: recency, dtype: int64

In [8]:
df[["recency"]].head()

   recency
0       10
1        6
2        7
3        9
4        2

In [9]:
df.loc[:,"recency"].head()

0    10
1     6
2     7
3     9
4     2
Name: recency, dtype: int64

In [10]:
df.iloc[:,0].head()

0    10
1     6
2     7
3     9
4     2
Name: recency, dtype: int64

# row indexing

In [11]:
df[0:2].head()

,recency,history_segment,history,mens,womens,zip_code,newbie,channel,segment,visit,conversion,spend,DM_category
0,10,2) $100 - $200,142.44,1,0,Surburban,0,Phone,Womens E-Mail,0,0,0.0,4
1,6,3) $200 - $350,329.08,1,1,Rural,1,Web,No E-Mail,0,0,0.0,11

In [12]:
df.iloc[0:2,:].head()

,recency,history_segment,history,mens,womens,zip_code,newbie,channel,segment,visit,conversion,spend,DM_category
0,10,2) $100 - $200,142.44,1,0,Surburban,0,Phone,Womens E-Mail,0,0,0.0,4
1,6,3) $200 - $350,329.08,1,1,Rural,1,Web,No E-Mail,0,0,0.0,11

# Boolean indexing

In [14]:
(df.recency < 7).head()

0    False
1     True
2    False
3    False
4     True
Name: recency, dtype: bool

In [16]:
df[ df.recency < 7 ].head()

,recency,history_segment,history,mens,womens,zip_code,newbie,channel,segment,visit,conversion,spend,DM_category
1,6,3) $200 - $350,329.08,1,1,Rural,1,Web,No E-Mail,0,0,0.0,11
4,2,1) $0 - $100,45.34,1,0,Urban,0,Web,Womens E-Mail,0,0,0.0,4
5,6,2) $100 - $200,134.83,0,1,Surburban,0,Phone,Womens E-Mail,1,0,0.0,1
11,1,3) $200 - $350,211.45,0,1,Urban,1,Phone,Womens E-Mail,0,0,0.0,1
12,5,5) $500 - $750,642.90,0,1,Surburban,1,Multichannel,Womens E-Mail,0,0,0.0,1

In [18]:
df[ (df.recency < 7) & (df.newbie == 0) ].head()

,recency,history_segment,history,mens,womens,zip_code,newbie,channel,segment,visit,conversion,spend,DM_category
4,2,1) $0 - $100,45.34,1,0,Urban,0,Web,Womens E-Mail,0,0,0.0,4
5,6,2) $100 - $200,134.83,0,1,Surburban,0,Phone,Womens E-Mail,1,0,0.0,1
13,2,2) $100 - $200,101.64,0,1,Urban,0,Web,Mens E-Mail,1,0,0.0,3
16,5,1) $0 - $100,29.99,1,0,Surburban,0,Phone,Mens E-Mail,0,0,0.0,2
22,2,2) $100 - $200,118.40,1,0,Surburban,0,Web,Mens E-Mail,1,0,0.0,2

In [20]:
df[df.recency < 7] = -100

In [21]:
df.head()

,recency,history_segment,history,mens,womens,zip_code,newbie,channel,segment,visit,conversion,spend,DM_category
0,10,2) $100 - $200,142.44,1,0,Surburban,0,Phone,Womens E-Mail,0,0,0.0,4
1,-100,-100,-100.00,-100,-100,-100,-100,-100,-100,-100,-100,-100.0,-100
2,7,2) $100 - $200,180.65,0,1,Surburban,1,Web,Womens E-Mail,0,0,0.0,1
3,9,5) $500 - $750,675.83,1,0,Rural,1,Web,Mens E-Mail,0,0,0.0,2
4,-100,-100,-100.00,-100,-100,-100,-100,-100,-100,-100,-100,-100.0,-100