# DAT210x - Programming with Python for DS

## Module2 - Lab4

Import and alias Pandas:

In [1]:
import pandas as pd

Load up the table from the link, and extract the dataset out of it. If you're having issues with this, look carefully at the sample code provided in the reading:

In [18]:
df1 = pd.read_html('http://espn.go.com/nhl/statistics/player/_/stat/points/sort/points/year/2015/seasontype/2')[0]
df1

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16
0,NaN,PP,SH,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,RK,PLAYER,TEAM,GP,G,A,PTS,+/-,PIM,PTS/G,SOG,PCT,GWG,G,A,G,A
2,1,"Jamie Benn, LW",DAL,82,35,52,87,1,64,1.06,253,13.8,6,10,13,2,3
3,2,"John Tavares, C",NYI,82,38,48,86,5,46,1.05,278,13.7,8,13,18,0,1
4,3,"Sidney Crosby, C",PIT,77,28,56,84,5,47,1.09,237,11.8,3,10,21,0,0
5,4,"Alex Ovechkin, LW",WSH,81,53,28,81,10,58,1.00,395,13.4,11,25,9,0,0
6,NaN,"Jakub Voracek, RW",PHI,82,22,59,81,1,78,0.99,221,10.0,3,11,22,0,0
7,6,"Nicklas Backstrom, C",WSH,82,18,60,78,5,40,0.95,153,11.8,3,3,30,0,0
8,7,"Tyler Seguin, C",DAL,71,37,40,77,-1,20,1.08,280,13.2,5,13,16,0,0
9,8,"Jiri Hudler, LW",CGY,78,31,45,76,17,14,0.97,158,19.6,5,6,10,0,0
10,NaN,"Daniel Sedin, LW",VAN,82,20,56,76,5,18,0.93,226,8.9,5,4,21,0,0
11,10,"Vladimir Tarasenko, RW",STL,77,37,36,73,27,31,0.95,264,14.0,6,8,10,0,0
12,NaN,PP,SH,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,RK,PLAYER,TEAM,GP,G,A,PTS,+/-,PIM,PTS/G,SOG,PCT,GWG,G,A,G,A
14,NaN,"Nick Foligno, LW",CBJ,79,31,42,73,16,50,0.92,182,17.0,3,11,15,0,0
15,NaN,"Claude Giroux, LW",PHI,81,25,48,73,-3,36,0.90,279,9.0,4,14,23,0,0
16,NaN,"Henrik Sedin, C",VAN,82,18,55,73,11,22,0.89,101,17.8,0,5,20,0,0
17,14,"Steven Stamkos, C",TB,82,43,29,72,2,49,0.88,268,16.0,6,13,12,0,0
18,NaN,"Tyler Johnson, C",TB,77,29,43,72,33,24,0.94,203,14.3,6,8,9,0,0
19,16,"Ryan Johansen, C",CBJ,82,26,45,71,-6,40,0.87,202,12.9,0,7,19,2,0
20,17,"Joe Pavelski, C",SJ,82,37,33,70,12,29,0.85,261,14.2,5,19,12,0,0
21,NaN,"Evgeni Malkin, C",PIT,69,28,42,70,-2,60,1.01,212,13.2,4,9,17,0,0
22,NaN,"Ryan Getzlaf, C",ANA,77,25,45,70,15,62,0.91,191,13.1,6,3,10,0,2
23,20,"Rick Nash, LW",NYR,79,42,27,69,29,36,0.87,304,13.8,8,6,6,4,1
24,NaN,PP,SH,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,RK,PLAYER,TEAM,GP,G,A,PTS,+/-,PIM,PTS/G,SOG,PCT,GWG,G,A,G,A
26,21,"Max Pacioretty, LW",MTL,80,37,30,67,38,32,0.84,302,12.3,10,7,4,3,2
27,NaN,"Logan Couture, C",SJ,82,27,40,67,-6,12,0.82,263,10.3,4,6,18,2,0
28,23,"Jonathan Toews, C",CHI,81,28,38,66,30,36,0.81,192,14.6,7,6,11,2,1
29,NaN,"Erik Karlsson, D",OTT,82,21,45,66,7,42,0.80,292,7.2,3,6,24,0,0
30,NaN,"Henrik Zetterberg, LW",DET,77,17,49,66,-6,32,0.86,227,7.5,3,4,24,0,0
31,26,"Pavel Datsyuk, C",DET,63,26,39,65,12,8,1.03,165,15.8,5,8,16,0,0
32,NaN,"Joe Thornton, C",SJ,78,16,49,65,-4,30,0.83,131,12.2,0,4,18,0,0
33,28,"Nikita Kucherov, RW",TB,82,28,36,64,38,37,0.78,190,14.7,2,2,13,0,0
34,NaN,"Patrick Kane, RW",CHI,61,27,37,64,10,10,1.05,186,14.5,5,6,16,0,0
35,NaN,"Mark Stone, RW",OTT,80,26,38,64,21,14,0.80,157,16.6,6,5,8,1,0
36,NaN,PP,SH,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37,RK,PLAYER,TEAM,GP,G,A,PTS,+/-,PIM,PTS/G,SOG,PCT,GWG,G,A,G,A
38,NaN,"Kyle Turris, C",OTT,82,24,40,64,5,36,0.78,215,11.2,6,4,12,1,0
39,NaN,"Alexander Steen, LW",STL,74,24,40,64,8,33,0.86,223,10.8,5,8,16,0,0
40,NaN,"Johnny Gaudreau, LW",CGY,80,24,40,64,11,14,0.80,167,14.4,4,8,13,0,0
41,NaN,"Anze Kopitar, C",LA,79,16,48,64,-2,10,0.81,134,11.9,4,6,18,0,0
42,35,"Radim Vrbata, RW",VAN,79,31,32,63,6,20,0.80,267,11.6,7,12,11,0,0
43,NaN,"Jaden Schwartz, LW",STL,75,28,35,63,13,16,0.84,184,15.2,4,8,8,0,2
44,NaN,"Filip Forsberg, C",NSH,82,26,37,63,15,24,0.77,237,11.0,6,6,13,0,0
45,NaN,"Jordan Eberle, RW",EDM,81,24,39,63,-16,24,0.78,183,13.1,2,6,15,0,0
46,NaN,"Ondrej Palat, LW",TB,75,16,47,63,31,24,0.84,139,11.5,5,3,8,1,1
47,40,"Zach Parise, LW",MIN,74,33,29,62,21,41,0.84,259,12.7,3,11,5,0,0

Next up, rename the columns so that they are _similar_ to the column definitions provided to you on the website. Be careful and don't accidentally use any column names twice. If a column uses special characters, you can replace them with regular characters to make it easier to work with:

In [19]:
df1.columns = ['RK', 'PLAYER', 'TEAM', 'GP', 'G', 'A', 'PTS', '+/-', 'PIM', 'PTS/G', 'SOG', 'PCT', 'GWG', 'PPG', 'PPA', 'SHG', 'SHA']

df1.head()

,RK,PLAYER,TEAM,GP,G,A,PTS,+/-,PIM,PTS/G,SOG,PCT,GWG,PPG,PPA,SHG,SHA
0,NaN,PP,SH,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,RK,PLAYER,TEAM,GP,G,A,PTS,+/-,PIM,PTS/G,SOG,PCT,GWG,G,A,G,A
2,1,"Jamie Benn, LW",DAL,82,35,52,87,1,64,1.06,253,13.8,6,10,13,2,3
3,2,"John Tavares, C",NYI,82,38,48,86,5,46,1.05,278,13.7,8,13,18,0,1
4,3,"Sidney Crosby, C",PIT,77,28,56,84,5,47,1.09,237,11.8,3,10,21,0,0

Get rid of any row that has at least 4 NANs in it. That is, any rows that do not contain player points statistics:

In [26]:
df1.dropna(thresh = (len(df1.columns) - 4), axis = 1)

"""df = df.dropna(axis=0,thresh=4)
print(df.head())
print(df.shape)"""

'df = df.dropna(axis=0,thresh=4)\nprint(df.head())\nprint(df.shape)'

At this point, look through your dataset by printing it. There probably still are some erroneous rows in there. What indexing command(s) will you use to select all rows EXCEPT those rows?

In [27]:
df1.drop([0, 1, 12, 13, 24, 25, 36, 37], axis = 0, inplace = True)

In [28]:
df1.head()

,RK,PLAYER,TEAM,GP,G,A,PTS,+/-,PIM,PTS/G,SOG,PCT,GWG,PPG,PPA,SHG,SHA
2,1,"Jamie Benn, LW",DAL,82,35,52,87,1,64,1.06,253,13.8,6,10,13,2,3
3,2,"John Tavares, C",NYI,82,38,48,86,5,46,1.05,278,13.7,8,13,18,0,1
4,3,"Sidney Crosby, C",PIT,77,28,56,84,5,47,1.09,237,11.8,3,10,21,0,0
5,4,"Alex Ovechkin, LW",WSH,81,53,28,81,10,58,1.00,395,13.4,11,25,9,0,0
6,NaN,"Jakub Voracek, RW",PHI,82,22,59,81,1,78,0.99,221,10.0,3,11,22,0,0

Get rid of the 'RK' column:

In [29]:
df1.drop('RK', axis = 1, inplace = True)

Make sure there are no holes in your index by resetting it. There is an example of this in the reading material. By the way, drop the original index.

In [30]:
df1.reset_index(inplace = True, drop = True)
print(df.head())

    0                  1    2   3   4   5   6   7   8     9    10    11  12  \
0    1     Jamie Benn, LW  DAL  82  35  52  87   1  64  1.06  253  13.8   6
1    2    John Tavares, C  NYI  82  38  48  86   5  46  1.05  278  13.7   8
2    3   Sidney Crosby, C  PIT  77  28  56  84   5  47  1.09  237  11.8   3
3    4  Alex Ovechkin, LW  WSH  81  53  28  81  10  58  1.00  395  13.4  11
4  NaN  Jakub Voracek, RW  PHI  82  22  59  81   1  78  0.99  221  10.0   3

   13  14 15 16
0  10  13  2  3
1  13  18  0  1
2  10  21  0  0
3  25   9  0  0
4  11  22  0  0

Check the data type of all columns, and ensure those that should be numeric are numeric.

In [31]:
print(df1.dtypes)
df1.GP = pd.to_numeric(df1.GP)
df1.G = pd.to_numeric(df1.G)
df1.A = pd.to_numeric(df1.A)
df1.PTS = pd.to_numeric(df1.PTS)
df1['+/-'] = pd.to_numeric(df1['+/-'])
df1.PIM = pd.to_numeric(df1.PIM)
df1['PTS/G'] = pd.to_numeric(df1['PTS/G'])
df1.SOG = pd.to_numeric(df1.SOG)
df1.PCT = pd.to_numeric(df1.PCT)
df1.GWG = pd.to_numeric(df1.GWG)
df1.PPG = pd.to_numeric(df1.PPG)
df1.PPA = pd.to_numeric(df1.PPA)
df1.SHG = pd.to_numeric(df1.SHG)
df1.SHA = pd.to_numeric(df1.SHA)
print(df1.dtypes)

PLAYER    object
TEAM      object
GP        object
G         object
A         object
PTS       object
+/-       object
PIM       object
PTS/G     object
SOG       object
PCT       object
GWG       object
PPG       object
PPA       object
SHG       object
SHA       object
dtype: object
PLAYER     object
TEAM       object
GP          int64
G           int64
A           int64
PTS         int64
+/-         int64
PIM         int64
PTS/G     float64
SOG         int64
PCT       float64
GWG         int64
PPG         int64
PPA         int64
SHG         int64
SHA         int64
dtype: object

Your dataframe is now ready! Use the appropriate commands to answer the questions on the course lab page.

In [33]:
print("The number of rows in the dataframe is: ", len(df1)) #40
print("There are", len(df1.PCT.unique()), "unique values in the PCT column." )#36
print("The value you get by adding the GP values at indices 15 and 16 of this table is", df1.ix[15, 'GP'] + df1.ix[16, 'GP'])

The number of rows in the dataframe is:  40
There are 36 unique values in the PCT column.
The value you get by adding the GP values at indices 15 and 16 of this table is 164

G:\officialWork\software\00_Anaconda\lib\site-packages\ipykernel_launcher.py:3: DeprecationWarning:
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  This is separate from the ipykernel package so we can avoid doing imports until